### ISSUE TITLE
Offer ability to run the program-under-test just once (no state space exploration) given a random seed

### ISSUE THREAD

**Issue by Bill** [upthewaterspout/fates#15]
Currently "The test is run repeatedly until all possible schedules are exercised". This is useful if you want FATES to find bugs. But finding bugs this way is impractical for anything but toy programs since the state space grows so rapidly as program complexity increases.

What if FATES had a less ambitions goal? Or, at least, what if FATES offered an option to run in a less ambitious mode? What if all I really wanted was _determinism_ without any state space exploration?

Make it possible to start a test with a seed value. That seed value will be used to generate randomness that will be used for all subsequent scheduling decisions by FATES. Instead of searching the state space, FATES offers a way to just run the program once.

In the absence of random number generator calls and I/O by the program-under-test, program behavior would be (almost) 100% determined by:

1. the byte code of the program-under-test
2. the version of the libraries it calls (e.g. JDK)
3. the Java VM version
4. the random seed provided at startup

Hold those four (4) variables constant and if the test passes once, it'll pass every time it's run, and if the test fails once, it'll fail every time it's run.

With this feature it would be possible to test more sophisticated programs: ones that did I/O and called the random number generator. To do that, the programs would use dependency injection to substitute actual I/O and random number classes with deterministic simulations.

**Comment by upthewaterspout** [comment]
This is actually possible with Fates 0.2.0. Fates has the concept of a StateExplorer. A StateExplorer is responsible for choosing between the available options at each decision point and deciding whether to do another run of the test at the end.

There are a couple of StateExplorer implementations. The DepthFirstExplorer does explore all possible choices. But there is also a RandomExplorer, which is pretty much what you describe  - although it has a configurable number of iterations.

So, to run with a fixed random seed once, you can use the RandomExplorer with the appropriate parameters:

```
new ThreadFates()
  .setExplorer(() -> new RandomExplorer(1, SEED))
  .run( yourMultiThreadedTest )
```

**Comment by upthewaterspout** [comment]
I'm marking this as complete, but if there are features you think are missing, feel free to reopen!

**Comment by Bill** [comment]
I'll try it. Thanks!
